# fly.toml app configuration file generated for t-tree-chat on 2025-06-18T18:16:15+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 't-tree-chat'
primary_region = 'iad'

[build]

[[mounts]]
  source = 'starter_pb_data'
  destination = '/app/pb_data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
