app = 't-tree-chat'
primary_region = 'iad'


[build]
[build.args]
VITE_POCKETBASE_BASE_URL = "https://t-tree-chat.fly.dev"

[[mounts]]
source = 't_tree_chat'
destination = '/app/pb_data'

[http_service]
force_https = true


[[vm]]
size = 'shared-cpu-1x'
